services:
  mysql:
    image: mysql:8
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_list
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
